[build]
  publish = "dist/querido-diario"
  command = "ng build --prod"

[[redirects]]
  from = "/*"
  to = "/pt/index.html"
  status = 200
  conditions = {Language = ["pt"]}

[[redirects]]
  from = "/*"
  to = "/en-US/index.html"
  status = 200
