[build]
  publish = "dist/querido-diario"
  command = "ng build --prod"

[[redirects]]
  from = "/pt/*"
  to = "/pt/index.html"
  status = 200

[[redirects]]
  from = "/en-US/*"
  to = "/en-US/index.html"
  status = 200
